name = "tdf_ada_83"
description = "A toy Ada 83 to TenDRA TDF translator"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/reznikmm/tdf-ada-83"
tags = ["backend", "compiler"]

executables = ["tdfada83"]

project-files = ["gnat/tdf_ada_83.gpr"]

[configuration]
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = "No"
development.contracts = "Yes"
"*".ada_version = "Ada83"
"*".debug_info = "Yes"

[[depends-on]]
gnat = "<2000" # Uses Ada 83 syntax absent in gnat gpl
