# SPDX-FileCopyrightText: 2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Build

on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: alire-project/setup-alire@v4
    - name: Build
      run: alr build
